server:
    port: 8588
    servlet:
        context-path: /

spring:
    datasource:
        url: jdbc:mysql://${DB_URL}
        username: ${DATASOURCE_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
profiles:
    active: local
    group:
        local: logging-type-condole, logging-level-local
        dev: logging-type-file, logging-level-dev